# Generated by Django 6.0.6 on 2026-08-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="department",
            field=models.CharField(max_length=100),
        ),
    ]
