# Generated by Django 6.0.6 on 2026-08-13 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attendance",
            options={"ordering": ["-date", "-id"]},
        ),
    ]
